### ISSUE TITLE
Als Suche für das Frontend

### ISSUE THREAD

**Issue by skerbis** [tbaddade/redaxo_watson#12]
würde mich freuen wenn die Lösung auch als Frontendsuche realisiert werden könnte.

**Comment by tbaddade** [comment]
@skerbis Kannst du kurz beschreiben wie du dir das vorstellst? Eher genauso wie im Backend oder gänzlich anders? Ich hatte mich gestern Abend mit @schuer geschrieben um seine Ansichten zu erfahren.

**Comment by skerbis** [comment]
Gerne wie im Backend, Anstelle des Watson Buttons, eine Lupe oder so, die man beliebig platzieren kann.  Man sollte es stylen können. 

Sollte es sehr viele Suchrgebnisse geben, sollte man evtl. auf eine ausführliche Liste gelangen können.  

Weitere Wünsche und Ideen: 
1. Suchen ermöglichen ab oder in einer bestimmten Kategorie
2. Nur nach Medien suchen (evtl. auch nach Kategorie), aber nicht in den Medien (wäre aber cool)
3. Schön wäre wenn die Communitylösung, wenn sie denn kommt auch beachtet wird, damit nicht geschützte Inhalte gefunden werden können.

**Comment by staabm** [comment]
Redest du von einer Lösung die einem im redaxo backend eingeloggten admin im Frontend was findet oder von einer suche die dem anonymen user im frontend suchergebnisse liefert?

**Comment by skerbis** [comment]
Ich rede von einer Suche für den Frontenduser (Besucher).

**Comment by staabm** [comment]
in welchen inhalten soll die suche dann suchen? mittels rex_search?

**Comment by skerbis** [comment]
In den REX_VALUES der Slices und evtl. ausgewählte Metas? REX_SEARCH für Redaxo 5 gibt es ja noch nicht - oder?

**Comment by skerbis** [comment]
Wie mach Watson das aktuell im Backend?

**Comment by tbaddade** [comment]
> Wie mach Watson das aktuell im Backend?

Watson sucht selbst in den Tabellen. Hier das Bsp. für die [Artikel](https://github.com/tbaddade/redaxo_watson/blob/master/lib/Watson/Workflows/Structure/ArticleSearch.php)

**Comment by skerbis** [comment]
GROUP BY   bulldog';
hehe

**Comment by alexplusde** [comment]
Es gibt jetzt eine Frontend-Suche. Hat sich das Issue damit erledigt?

**Comment by tbaddade** [comment]
Gute Frage. Eventuell kann search_it eine Api bereitstellen, damit der Watson als Suche im Frontend genutzt werden kann. Muss ja nicht immer als Overlay dargestellt werden, kann auch als normale Sucheingabe auftauchen.

**Comment by alexplusde** [comment]
@tyrant88 was meinst du? Sehe ich eher nicht kommen. Aber vlt. kann man sich was für die AJAX-Suche von Watson abschauen.

**Comment by skerbis** [comment]
Für kleine Präsenzen ist eine indizierte Suche evtl. etwas überdimensioniert, daher würde es mir gefallen direkt in der DB zu suchen und Watson bietet sich da an.

**Comment by tbaddade** [comment]
Wenn ich mir das so recht überlege, ginge das alles schon mit Watson und search_it. Ich werde mich mal dran setzen.

**Comment by tyrant88** [comment]
Ich habe ehrlich gesagt Watson noch nie benutzt. Thomas kann das am Besten beurteilen, was die Unterschiede sind.

**Comment by paddle07** [comment]
@tbaddade Gibt es da schon eine Frontend Version? Hätte auch Interesse daran.

**Comment by alexplusde** [comment]
@paddle07 was fehlt dir bei `Search it`?

**Comment by paddle07** [comment]
Brauche eine Typeahead/Ajax Suche für das Frontend. Ähnlich wie Watson im Backend funktioniert.

**Comment by alexplusde** [comment]
Das lässt sich auch mit `Search it` realisieren. Für RexSearch habe ich dazu mal einen Post verfasst:
https://redaxo.org/forum/addons-r4-f30/addon-rexsearch-fulltext-search-addon-t12965-s690.html#p119187, allerdings nicht zu 100% elegant gelöst.

Man könnte bspw. nur ein JSON-Objekt zurückgeben. Ich möchte das demnächst umbauen auf `Search it` und als Tutorial in die Doku eintragen. Vielleicht magst du dich ja beteiligen? 
https://github.com/FriendsOfREDAXO/search_it/issues/60

**Comment by alexplusde** [comment]
@paddle07 es gibt jetzt ein AJAX-Plugin für `search_it`

Zum ursprünglichen Thema: search_it über eine zusätzliche "Live-Suche" (ohne Index) zu erweitern, wäre ja durchaus machbar. Die Frage ist: Braucht man dafür zwingend Watson?

**Comment by skerbis** [comment]
Von meiner Seite her hat es sich erledigt.
