### ISSUE TITLE
yform-Tabellen und Datensätze durchsuchen

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_watson#14]
(Ich weiß, mein Wunschzettel ist groß, aber als Feature-Request kannst du es ja mal im Auge behalten.)

**Comment by alexplusde** [comment]
Ist das tatsächlich auch im Installer drin? Funktioniert nämlich nicht bei mir, oder muss ich da noch etwas beachten?

**Comment by tbaddade** [comment]
> Ist das tatsächlich auch im Installer drin? 
Nein.

**Comment by alexplusde** [comment]
Kann man dich beim Release in den Installer unterstützen?

**Comment by tbaddade** [comment]
> Kann man dich beim Release in den Installer unterstützen?

Ist soeben released worden.

**Comment by alexplusde** [comment]
Danke dir!
