### ISSUE TITLE
Nach Update auf Redaxo 5.3 - Symbol weg

### ISSUE THREAD

**Issue by skerbis** [tbaddade/redaxo_watson#17]
![bildschirmfoto 2017-02-14 um 17 03 07](https://cloud.githubusercontent.com/assets/791247/22937022/8f6e3c90-f2d7-11e6-8953-88de94812028.png)

**Comment by tbaddade** [comment]
Kann ich beheben, ist aber ein REDAXO 5.3 "Fehler".

**Comment by staabm** [comment]
d.h. was ist die ursache dafür in r5.3?

**Comment by tbaddade** [comment]
> d.h. was ist die ursache dafür in r5.3?

Wegen diesen Zeilen[[1]](https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/be_style/boot.php#L48-L56) wird das CSS des Backends jetzt als letztes geladen und überschreibt ggf. vorherige Anweisungen.

Hintergrund dazu ist dieses Issue[[2]](https://github.com/redaxo/redaxo/issues/821)
Es wird geschaut, ob sich irgendein AddOn/Plugin an den EP registriert hat. Ist dem nicht so, wird die `be_style/bad-styles.css` Datei geladen, da diese ohne Definitionen eines Plugins/Themes kompiliert wurde. Die `be_style/styles.css` hat beim kompilieren Definitionen vom Plugin `/be_style/redaxo/` entgegengenommen. Will man das korrekt und sauber haben wollen, müsste man beim aktivieren/deaktivieren des Plugins bzw. die sich zuvor an den EP gehangen haben das Kompilieren neu starten. Das will man online wirklich nicht haben, da es bis hin zu einem 500er laufen kann.

[1] https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/be_style/boot.php#L48-L56
[2] https://github.com/redaxo/redaxo/issues/821

**Comment by staabm** [comment]
Bitte testen, sollte mit dem be_style update von gestern nacht nicht mehr passieren

**Comment by skerbis** [comment]
Das be_style update verursachte bei mir einen Fehler. Nach einem Reload war aber alles wieder ok und das Symbol wieder da. https://github.com/redaxo/redaxo/issues/1051

**Comment by tbaddade** [comment]
> Das be_style update verursachte bei mir einen Fehler.

Welchen Fehler?

**Comment by tbaddade** [comment]
das verursachte der Core und ist mit der Version 5.3 behoben.
