### ISSUE TITLE
Whooops unter PHP 5.5

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_watson#27]
Genaue Fehlermeldung kann ich nicht mehr geben, da das ein Live-System war und schnellstmöglich vom Hoster auf PHP7 umgestellt wurde.

Möglicher Workaround: Mindestanforderung für die PHP-Version bei der Installation erhöhen.

**Comment by staabm** [comment]
unter php 5.4 sehe ich folgenden error (obs das gleiche ist wie bei php5.5 weiß ich nicht, hab keins greifbar)

```
mstaab@vStaab12:~/dev/watson$ find . -type f -name '*.php' -exec php -l {} \; |grep -v "No syntax errors detected"
PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in ./lib/Watson/Foundation/Watson.php on line 71
Errors parsing ./lib/Watson/Foundation/Watson.php
```

**Comment by staabm** [comment]
aber das kommt gut hin, weil variadic args ist php 5.6+

https://secure.php.net/manual/en/functions.arguments.php#functions.variable-arg-list

**Comment by tbaddade** [comment]
Danke dir @staabm

**Comment by alexplusde** [comment]
Ist immer noch so im Installer

**Comment by staabm** [comment]
bisher gab es keinen fix dazu... ich vermute PR welcome.

**Comment by alexplusde** [comment]
Muss es denn einen Fix geben? Reicht es nicht, die Mindest-PHP-Version anzuheben?

**Comment by staabm** [comment]
wenn man nur die min version anhebt werden alle die php5.5 haben die kaputte version bekommen (als ein release vor dem zukünftigen) und dann einen error haben

**Comment by tbaddade** [comment]
> wenn man nur die min version anhebt werden alle die php5.5 haben die kaputte version bekommen (als ein release vor dem zukünftigen) und dann einen error haben.

normalerweise steht im Installer nur die letzte Version zur Auswahl. Wenn man die PHP Version anhebt, dann dürfte die neue Version gar nicht installiert werden können sofern dort PHP 5.5 vorhanden ist. Es betrifft dann nur diejenigen, die das AddOn bereits installiert haben oder?

**Comment by staabm** [comment]
@gharlan ich vermute im Installer steht "je php" version die "neuste" version zur Verfügung, oder?

**Comment by gharlan** [comment]
So intelligent ist der Installer leider nicht. Er zeigt einfach ALLE Versionen an, die der Addon-ersteller auf "online" stehen hat. Wenn man versucht auf eine Version zu updaten, die nicht zu der Umgebung (php etc.) passt, wird abgebrochen. Man muss sich also selbst die richtige Version rausssuchen.

**Comment by alexplusde** [comment]
Also wäre mein Vorschlag, die aktuelle Version aus dem Installer zu nehmen und mit neuer Mindestversion hochzuladen möglich - sogar ohne einen neuen "Release" zu machen.
