### ISSUE TITLE
javascript:newPoolWindow() Fehler

### ISSUE THREAD

**Issue by godsdog** [tbaddade/redaxo_watson#29]
Beim klicken auf einer Datei aus dem Medienpool im Watson Ergebniss erscheint kurz das Medienpool Popup Fenster und schließt sich sofort, da die Seite weitergeleitet wird auf: javascript:newPoolWindow('index.php?page=mediapool/media&file_id=1')
Steht dann in der Adresszeile.

Evtl. fehlt ein "return false" beim Aufruf von newPoolWindow()?

REDAXO 5.5.1

**Comment by tbaddade** [comment]
Kann ich so nicht nachvollziehen. Eventuell wurde der Fehler bereits behoben. Gern Issue wieder eröffnen, wenn der Fehler beim nächsten Release noch vorhanden sein sollte.
