### ISSUE TITLE
Klick auf Treffer führt – scheinbar regellos – mal zu Edit, mal zur Strukturansicht

### ISSUE THREAD

**Issue by fitzliputz** [tbaddade/redaxo_watson#30]
Der Fehler tritt auf mehreren Servern (Redaxo 5.4 und 5.5.1) auf, Umfang der Websites zwischen 20 und 1500 Artikeln. Die Suche selbst klappt in aller Regel zuverlässig und sehr schnell, mitunter wird aber unversehens nichts mehr gefunden – auch nicht das, was Sekunden zuvor noch da war.

Das eigentliche Symptom ist aber das folgende: Blättert man mit den Pfeiltasten durch die Trefferliste und öffnet den Link zum gefundenen Artikel mit Return, werden unterschiedliche Aktionen ausgeführt:

(1) Man landet beim Artikel-Edit des Treffer. Das würde ich als erwartbares Verhalten bezeichnen.

(2) Man landet in der Strukturansicht der Kategorie, in der sich der gefundene Artikel befindet. Diese Seltsamkeit mag noch angehen, wenn in der Kategorie nur wenige Artikel sind, bei einigen hundert wird es spätestens sinnlos.

Wann passiert (1) und wann (2)? Keine Ahnung. Wir versuchen seit einigen Tagen mit mehreren erfahrenen Leuten ein System zu erkennen, es will uns nicht gelingen. Mal (1), mal (2), egal ob die Artikel Inhalte enthalten oder nicht, online oder offline sind und unabhängig von der Kategorie-Ebene. In ein und derselben Trefferliste führt Klick auf Treffer a bis e zum Ziel (1) und Treffer f zu (2) – bei praktisch identisch aufgebauten Artikeln derselben Kategorie.

Ganz bizarr:  Es ist mitunter sogar ein Unterschied, mit welchem Suchbegriff gefunden wurde. Bei Artikeln mit dem Muster-Titel 'Foo Bar' führt der Klick auf den Treffer zu (1), wenn man nach 'foo', und zu (2)  wenn man nach 'bar' sucht. Derselbe Artikel wohlgemerkt, der in beiden Fällen der einzige Treffer ist.

Watson wäre eigentlich ein absoluter Heuler, wenn er sich auf Verhalten (1) beschränken würde – so wie er sich benimmt, ist er leider nicht zu gebrauchen, was wirklich extrem schade ist.

**Comment by tbaddade** [comment]
Watson durchsucht den Artikelinhalt und die Artikelnamen. Findet Watson etwas in den Ctypes landet man im Content ansonsten in der Strukturansicht.

Die dazugehörigen Zeilen sind hier:
https://github.com/tbaddade/redaxo_watson/blob/master/lib/Watson/Workflows/Structure/ArticleSearch.php#L183-L189

**Comment by fitzliputz** [comment]
Danke für die Info – da muss man erstmal drauf kommen ;-) Was wie gesagt weder mir gelang, noch Redaktionsleuten, die damit arbeiten … egal, es ließ sich jetzt leicht anpassen und alles ist gut.

Worin der Nutzen bestehen soll, in der Strukturansicht zu landen, kapiere ich offen gestanden nicht. Zumal dann, wenn zig oder hunderte Artikel in einer Kategorie enthalten sind und die Artikel auch noch paginiert erscheinen, ist kaum ein Zusammenhang zwischen Treffer und Linkziel des Treffers zu erkennen. Ich selbst kann mit der Anpassung der paar Zeilen gut leben, aber wenn ich mir einen Vorschlag erlauben darf, dann denn, dass es ein Setting gibt, mit dem man festlegt, wo man nach dem Klick auf den Treffer landen möchte. Oder spricht irgendetwas Gravierendes dagegen, immer im Content zu landen?

**Comment by tbaddade** [comment]
Wenn im Content nichts vorhanden ist, leerer Artikel, warum sollte man denn dort landen? Denn dann wurde nur der Artikelname gefunden. Wenn das bei euch nicht so sein sollte, wäre es ein Fehler.

**Comment by fitzliputz** [comment]
Kein Content muss nicht notwendig ein leerer Artikel sein. Wr machen viele Websites für Organsiationen, die primär Veranstalter von was auch immer sind, mit umfangreichen Programmkalendern, die organisatorisch bedingt zahlreiche Metadaten-Felder beinhalten. Klar, aus Sicht der Suche heißt kein Content leer – die Redakteure sehen das aber begreiflicherweise anders ;-)
