### ISSUE TITLE
Featurewunsch:: Suche auch nach sked-Terminen 

### ISSUE THREAD

**Issue by skerbis** [tbaddade/redaxo_watson#31]
bzw. in sked-Tabelle

**Comment by tbaddade** [comment]
Dafür gibt es in Watson einen ExtensionPoint. Sked kann also seine eigene Suche für Watson mitbringen.

Extension Point
https://github.com/tbaddade/redaxo_watson/blob/master/lib/Watson/Foundation/Watson.php#L80

Hier werden die mitgelieferten Workflows geladen und dann dem EP übergeben.
https://github.com/tbaddade/redaxo_watson/blob/master/lib/Watson/Foundation/Watson.php#L78

Registrierung der Provider (für dich eher uninteressant, aber genauso müsstest du dein Provider notieren)
https://github.com/tbaddade/redaxo_watson/blob/master/package.yml#L20

Und für den Sked Workflow einfach einen bestehenden Workflow kopieren und dann anpassen
https://github.com/tbaddade/redaxo_watson/tree/master/lib/Watson/Workflows/YForm

**Comment by tbaddade** [comment]
Vielleicht noch erwähnenswert wie du deine Suche testen könntest.

Im Browser einfach diese Url aufrufen
`/redaxo/index.php?page=watson&watson_query=QUERY` (`QUERY > Sucheingabe`)
Falls ein 404 oder was auch immer kommt, wirst du das im WatsonAgent nicht sehen. Da würde dann "kein Ergebnis" kommen

**Comment by skerbis** [comment]
@alexplusde hatte keine Zeit
