### ISSUE TITLE
Kompatibilität zu YRewrite

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_watson#33]
Bei mir wird `/domain.de/.../.../` ausgegeben. Vlt. wird die Artikel-ID nicht mit `rex_getUrl()` durchlaufen?

**Comment by tbaddade** [comment]
Wann genau wird diese URL erzeugt. Was wird gefunden (Artiklel, Slice, Kategorie, YForm Datensatz etc.) und sollte wohin verlinkt werden? Welche URL wäre korrekt?

**Comment by alexplusde** [comment]
Ein Artikel.

![image](https://user-images.githubusercontent.com/3855487/41766098-552aa196-7606-11e8-8e79-41f34eac0079.png)

**Comment by alexplusde** [comment]
Cool, Danke!
