### ISSUE TITLE
Suchergebnis: Hover > Vorschau

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_watson#34]
Da ein Klick direkt zum Artikel / Datensatz führt, kann man nur mit den Cursor-Tasten die Vorschau sehen. Hier wäre es schöner, zumindest mit der Maus hovern zu können, um die Vorschau zu triggern.

**Comment by tbaddade** [comment]
Du meinst die kleine Vorschau rechts? Nicht die große die angezeigt wird, wenn du die Leertaste drückst?

**Comment by skerbis** [comment]
Hover kann zu ungewollten oder komischen Effekten führen. Evtl. ein on click auf ein Auge Pfeile oder Ähnliches?

**Comment by tbaddade** [comment]
Ich weiß nicht was hier das bessere Verhalten sein könnte. 
Ich arbeite hier zumeist mit der Tastatur. 

Gibt es weitere Ideen?

**Comment by staabm** [comment]
wenn aktionen nur via tastatur auszulösen sind hat man oft das problem dass die user die features gar nicht finden.

Am besten wären knöpfe o.ä. (Wie von skerbis vorgeschlagen, z.b. Mit „auge“)

**Comment by tbaddade** [comment]
Hover fände ich gut. Mag jemand einen PR umsetzen?
