### ISSUE TITLE
countable()-Warning in result.php

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_watson#42]
count() [<a href='https://php.net/manual/function.count'>function.count</a>]: Parameter must be an array or an object that implements Countable | redaxo/src/addons/watson/lib/Watson/Foundation/Result.php

Im Systemlog. Wodurch es verursacht wird, kann ich nicht sagen.

**Comment by alexplusde** [comment]
Zeile 42 (true story)

**Comment by tbaddade** [comment]
close via 237e9955b055892ab01dc85359e2d4031be2be40
