### ISSUE TITLE
Suche nach Produkt: Artikelnummer

### ISSUE THREAD

**Issue by rkemmere** [tbaddade/redaxo_watson#43]
Es ist aktuell nicht möglich nach dem String "1351" zu suchen.

`if (count($command_parts) == 1 && (int) $command_parts[0] >= 1) {`

Diese Zeile sorgt dafür das anschließend die where Bedingung überschrieben wird und dann nach einer ArtikelID mit 1351 gesucht wird.

Dabei ist doch die Where Bedingung vorher **(a.id LIKE "%1351%") OR (a.name LIKE "%1351%")** richtig.

Könnte man dort eine andere Logik verbauen?

**Comment by tbaddade** [comment]
> Diese Zeile sorgt dafür das anschließend die where Bedingung überschrieben wird

Wäre gut, wenn du du die Zeile verlinken könntest.

**Comment by rkemmere** [comment]
https://github.com/tbaddade/redaxo_watson/blob/350550cc962f6bd9f03cfc1fede83db951ee9021/lib/Watson/Workflows/Structure/ArticleSearch.php#L82

**Comment by tbaddade** [comment]
Wo genau suchst du etwa? Die Slices werden später durchsucht. Wenn dort deine Id dabei ist, sollte der Artikel auch erscheinen. Was durchaus sein kann, das dein String zu oft vorkommt und der tatsächlich gesuchte Artikel nicht in der Liste mit erscheint.

**Comment by rkemmere** [comment]
Ich habe 50 Artikel in einer Kategorie und die namen der Artikel sind beispielsweise BRAND 5500.
