### ISSUE TITLE
Diverse Einträge im Systemlog

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_watson#48]
Bei der einfachen Eingabe von Buchstaben, Zahlen, Texte.

02.04.2019 12:23:35 | rex_sql_exception | Error while executing statement " SELECT a.id, a.clang_id, CONCAT(a.id, " | ", a.clang_id) as bulldog FROM rex_article AS a WHERE () OR ( GROUP BY bulldog LIMIT 20"! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') OR () GROUP BY bulldog LIMIT' at line 1 | redaxo/src/core/lib/sql/sql.php
-- | -- | -- | -- | --
02.04.2019 12:23:34 | Warning | count() [<a href='https://php.net/manual/function.count'>function.count</a>]: Parameter must be an array or an object that implements Countable | redaxo/src/addons/watson/lib/Watson/Foundation/Result.php | 42
02.04.2019 12:23:34 | Warning | count() [<a href='https://php.net/manual/function.count'>function.count</a>]: Parameter must be an array or an object that implements Countable | redaxo/src/addons/watson/lib/Watson/Foundation/Result.php | 42
02.04.2019 12:23:34 | Warning | count() [<a href='https://php.net/manual/function.count'>function.count</a>]: Parameter must be an array or an object that implements Countable | redaxo/src/addons/watson/lib/Watson/Foundation/Result.php | 42
02.04.2019 12:23:34 | Warning | count() [<a href='https://php.net/manual/function.count'>function.count</a>]: Parameter must be an array or an object that implements Countable | redaxo/src/addons/watson/lib/Watson/Foundation/Result.php | 42
02.04.2019 12:23:34 | Warning | count() [<a href='https://php.net/manual/function.count'>function.count</a>]: Parameter must be an array or an object that implements Countable | redaxo/src/addons/watson/lib/Watson/Foundation/Result.php | 42

**Comment by skerbis** [comment]
bitte die count() Sache fixen @tbaddade

**Comment by staabm** [comment]
Ist dieses problem hier ggf auch verursacht durch ein reserviertes keyword in spaltennamen, wie in https://github.com/tbaddade/redaxo_watson/issues/49 beschrieben?

**Comment by skerbis** [comment]
Vielleicht ist entries einfach nicht countable an dieser stelle https://github.com/tbaddade/redaxo_watson/blob/6d7420df313982eab94704c944b27d2e9b36802a/lib/Watson/Foundation/Result.php#L42

**Comment by skerbis** [comment]
wenn ich stattdessen '  if ($entries) {`'... einsetze ist alles ok

**Comment by alexplusde** [comment]
Genau. Wichtig zu wissen ist, dass diese Meldung erst in PHP 7.3 eine Warning erzeugt, in PHP 7.2 hat das vermutlich nur zu einer notice geführt.
