### ISSUE TITLE
Rechte beachten - Artikelrechte der Redakteure beachten

### ISSUE THREAD

**Issue by dergel** [tbaddade/redaxo_watson#5]

**Comment by skerbis** [comment]
Nicht nur die Artikelrechte, es werden z.B. Module angezeigt, obwohl der User kein Admin ist.

**Comment by tbaddade** [comment]
@skerbis R4 oder R5?

**Comment by skerbis** [comment]
R5 - bin ich im falschen Repo?

**Comment by tbaddade** [comment]
> bin ich im falschen Repo?

Nein. Beide Versionen sind als Branch dabei und wollte das Issue nur richtig labeln. Danke dir.
