### ISSUE TITLE
Warning wg. Count()

### ISSUE THREAD

**Issue by skerbis** [tbaddade/redaxo_watson#51]
PHP: 7.2.18

count() [<a href='https://php.net/manual/function.count'>function.count</a>]: Parameter must be an array or an object that implements Countable

redaxo/src/addons/watson/lib/Watson/Foundation/Result.php | 42

**Comment by dpf-dd** [comment]
Auch gerade festgestellt. Seit PHP 7.2 wirft Watson eine Warning:
```ZEILE 42: count() [<a href='https://php.net/manual/function.count'>function.count</a>]: Parameter must be an array or an object that implements Countable```

**Comment by dpf-dd** [comment]
Hab ich auch gerade festgestellt: Warning in `Zeile 42` der `redaxo/src/addons/watson/lib/Watson/Foundation/Result.php`

**Comment by skerbis** [comment]
Ok sind hier gesammelt: https://github.com/tbaddade/redaxo_watson/issues/48
