### ISSUE TITLE
Watson-Button in und ohne Quicknavi

### ISSUE THREAD

**Issue by skerbis** [tbaddade/redaxo_watson#69]
**Ohne Quicknavi: Aktuell schlecht erkennbar.** 
<img width="611" alt="Bildschirmfoto 2022-07-29 um 14 08 25" src="https://user-images.githubusercontent.com/791247/181755371-67d6c4fa-9a31-48ff-9a6c-60f4e3aa7094.png">

**Mit Quicknavi**

<img width="329" alt="Bildschirmfoto 2022-07-29 um 14 11 59" src="https://user-images.githubusercontent.com/791247/181755846-16d42add-4f27-443a-8c85-0ddcf8f4f00b.png">
In Quicknavi wird das Symbol nicht mehr ausgegeben da das Symbol wohl nicht mehr per CSS eingefügt wird. 

**Request:**
Bitte auch trigger class von styles trennen. Das ermöglicht mir auch eine einfachere Übernahme oder Gestaltung in Quicknavi.

**Comment by tbaddade** [comment]
> Bitte auch trigger class von styles trennen. Das ermöglicht mir auch eine einfachere Übernahme oder Gestaltung in Quicknavi.

getriggert wird jetzt über `data-watson-toggle="agent"`. Wenn du aber die Methode Watson::getToggleButton verwendest ([siehe PR](https://github.com/FriendsOfREDAXO/quick_navigation/pull/144)), brauchst du dir darüber keine Gedanken mehr machen.

**Comment by skerbis** [comment]
Danke schön
