### ISSUE TITLE
Alternative für den Hotkey anbieten

### ISSUE THREAD

**Issue by tbaddade** [tbaddade/redaxo_watson#7]
via E-Mail:
kann man / könntest Du in Watson auch einen anderen Shortcut zum Aktivieren anbieten?
Bei mit Ctrl + Space nämlich mit Alfred belegt.

**Comment by skerbis** [comment]
Ein Button zum Aufruf ohne Shortcut wäre auch toll.

**Comment by tbaddade** [comment]
> Ein Button zum Aufruf ohne Shortcut wäre auch toll.

ist ab Redaxo 5 jetzt dabei
