### ISSUE TITLE
Großes Icon im Installer unmittelbar nach Installation von Watson

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_watson#70]
![image](https://user-images.githubusercontent.com/3855487/182025546-a0d49feb-94a1-465d-843f-cb78799d5484.png)

**Comment by tbaddade** [comment]
Passiert, da das CSS vom Core nicht in den `<head>` geladen wird. Pjax-Ding. Weiß nicht, wie man das beheben sollte.

Vielleicht hat @gharlan eine Idee.

**Comment by gharlan** [comment]
> Vielleicht hat @gharlan eine Idee.

Da du das SVG ja direkt inline reinsetzt, kannst du es nicht mit abgewandelter Viewbox reinsetzen?

**Comment by tbaddade** [comment]
Bei RexStan ist das Problem ebenso vorhanden.
