### ISSUE TITLE
`Watson::getTable` nicht rexstan kompatibel

### ISSUE THREAD

**Issue by staabm** [tbaddade/redaxo_watson#73]
da in watson `Watson::getTable` statt ` rex::getTable($table);` verwendet wird, kann rexstan den code/die sql queries nicht analysieren.

wenn ich mir die methode so ansehe, sehe ich keinen vorteil gegenüber der core methode:

https://github.com/tbaddade/redaxo_watson/blob/3cc7fdec05cb06c42368f10dc18f2c571a31aeb6/lib/Watson/Foundation/Watson.php#L193-L203

daher für dich als info: falls du direkt mit `rex::getTable($table)` arbeiten würdest, könnte rexstan die codebase besser verstehen.

kannste natürlich gerne ignorieren und einfach schließen, bin grad nur zufällig drüber gestolpert, weil der code im slack verlinkt war

**Comment by tbaddade** [comment]
Danke dir
